#!/usr/bin/env bash
# Generate .env with random credentials for docker-compose (never commit .env).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ROOT}/.env"

if [[ -f "$ENV_FILE" && "${ELDA_FORCE_REGEN_ENV:-0}" != "1" ]]; then
  echo "==> .env already exists: ${ENV_FILE}"
  exit 0
fi

if ! command -v openssl &>/dev/null; then
  echo "ERROR: openssl required to generate credentials" >&2
  exit 1
fi

rand_hex() {
  openssl rand -hex 24
}

PG_USER="${ELDA_POSTGRES_USER:-elda}"
PG_PASS="$(rand_hex)"
PG_DB="${ELDA_POSTGRES_DB:-elda}"
MINIO_USER="${ELDA_MINIO_ROOT_USER:-elda}"
MINIO_PASS="$(rand_hex)"
MINIO_SECRET="$(rand_hex)"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/init_compose_env.sh — local only, do not commit

ELDA_POSTGRES_USER=${PG_USER}
ELDA_POSTGRES_PASSWORD=${PG_PASS}
ELDA_POSTGRES_DB=${PG_DB}

ELDA_MINIO_ROOT_USER=${MINIO_USER}
ELDA_MINIO_ROOT_PASSWORD=${MINIO_PASS}
ELDA_MINIO_ACCESS_KEY=${MINIO_USER}
ELDA_MINIO_SECRET_KEY=${MINIO_SECRET}
ELDA_MINIO_BUCKET=elda-artifacts
ELDA_MINIO_SECURE=false
ELDA_MINIO_ENDPOINT=127.0.0.1:9000

ELDA_REDIS_URL=redis://127.0.0.1:6379/0
ELDA_MILVUS_HOST=127.0.0.1
ELDA_MILVUS_PORT=19530
ELDA_WORKER_START_DELAY=3

ELDA_DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASS}@127.0.0.1:5432/${PG_DB}
EOF
chmod 600 "$ENV_FILE"
echo "==> wrote ${ENV_FILE} (mode 600, random postgres/minio credentials)"
